######################################################################
# Automatically generated by qmake (3.0) Thu Aug 10 16:40:44 2017
######################################################################

TEMPLATE = app
TARGET = browser_demo
INCLUDEPATH += .

QT += gui widgets network webchannel

CONFIG += c++11
CONFIG += link_pkgconfig
PKGCONFIG += libqcef

# Input
HEADERS += browser_window.h
SOURCES += browser_window.cpp \
           main.cpp
